### PR TITLE
Content type issue & fix

### PR DESCRIPTION
**Pull request by deep-spaced**
Hello! 

I've been using your library in a production app for six months now and in general, it's been fantastic! I've run into one little snag, though, and I think I found the fix. In the app I've been serving liquid-based RSS views from the database and setting the content type in the controller to 'application/rss+xml'. However, the content type of the served page has been set to `text/html` regardless of where I set it. For example, none of these work:

``` ruby
    respond_to do |format|
      format.html {}
      format.rss { render layout: false, content_type: 'application/rss+xml' }
    end     

    format.rss { 
      response.headers['content_type'] = 'application/rss+xml'
      render layout: false
    }
```

Even setting it in an `after_filter` didn't do anything. After some fiddling, I traced it to here:

https://github.com/yoolk/liquid-rails/blob/master/lib/liquid-rails/template_handler.rb#L16

In order to get testing to work locally and on Travis, I had to do the following:
- Updated local Ruby version to 2.2.5 and set to use generic .ruby-version syntax
- Updated Travis to test against Ruby 2.2.5
- Removed Guard as a dependency for Travis due to ruby_dep not working prior to Ruby 2.2

To fix this issue, here's what I did:
- Added a test for the content type
- Removed line 16 of `template_handler.rb` that set the content type

Let me know if this makes sense. Thanks for putting together this great library!

### CODE REVIEW

**Comment by GimliLongBow** [comment]
Weird. The build passed on my Travis setup... Sorry, not sure what happened here!

https://travis-ci.org/GimliLongBow/liquid-rails/jobs/128042969

**Comment by GimliLongBow** [comment]
@chamnap do you have any thoughts on why the test is failing on this side and not on mine? Thanks!

**Comment by chamnap** [comment]
Thanks for the PR. I'll check when i have time. Too busy recently.

**Comment by chamnap** [comment]
I've integrated into the master branch now.

**Pull request closed without merging**
